Repository d4l-data4life/hc-fhir-sdk-java, pull requests merged in 2020-11, with the labels that each got.

#11 Add fastlane actions for r4 and rename previous action to stu3
  fastlane/Fastfile
  fastlane/actions/fhir_java_r4.rb
  fastlane/actions/fhir_java_stu3.rb
Labels: enhancement

#16 Add migration information for version 0.7.0 to 1.0.0
  MIGRATION.md
Labels: documentation

#15 Add cleanup after r4 model gen
  CHANGELOG.md
  MIGRATION.md
  fastlane/actions/fhir_java_r4.rb
Labels: enhancement

#17 Bump dependencies
  CHANGELOG.md
  README.adoc
  build.gradle.kts
  buildSrc/src/main/java/Versions.kt
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: enhancement

#18 Prepare release 1.0.0
  .github/CODEOWNERS
  CHANGELOG.adoc
  CHANGELOG.md
  MIGRATION.adoc
  README.adoc
  buildSrc/src/main/java/LibraryConfig.kt
Labels: documentation, enhancement

#19 Change migration guide for 1.0.0
  CHANGELOG.adoc
  MIGRATION.adoc
Labels: documentation
