Repository d4l-data4life/hc-fhir-sdk-java, pull requests merged in 2021-01, with the labels that each got.

#22 Add maven publishing
  .github/ISSUE_TEMPLATE.md
  .github/workflows/d4l-ci-latest-version.yml
  .github/workflows/d4l-ci-publish-release.yml
  .github/workflows/d4l-ci-pull-request-validation.yml
  .github/workflows/d4l-ci.yml
  .idea/codeStyles/Project.xml
  .idea/compiler.xml
  .idea/vcs.xml
  CHANGELOG.adoc
  README.adoc
  build.gradle.kts
  buildSrc/build.gradle.kts
  buildSrc/settings.gradle.kts
  buildSrc/src/main/java/LibraryConfig.kt
  buildSrc/src/main/java/ProjectConfig.kt
  buildSrc/src/main/kotlin/Dependencies.kt
  buildSrc/src/main/kotlin/LibraryConfig.kt
  buildSrc/src/main/kotlin/ProjectConfig.kt
  buildSrc/src/main/kotlin/Versions.kt
  buildSrc/src/main/kotlin/scripts/publishing-config.gradle.kts
  buildSrc/src/main/kotlin/scripts/publishing.gradle.kts
  buildSrc/src/main/kotlin/scripts/versioning.gradle.kts
  fhir-doc/build.gradle
  fhir-java/build.gradle.kts
  gradle/wrapper/gradle-wrapper.properties
Labels: enhancement

#23 Prepare release 1.2.0
  CHANGELOG.adoc
  README.adoc
  buildSrc/src/main/kotlin/LibraryConfig.kt
  buildSrc/src/main/kotlin/scripts/publishing-config.gradle.kts
  buildSrc/src/main/kotlin/scripts/publishing.gradle.kts
  fhir-java/build.gradle.kts
Labels: documentation

#24 Fix Canonical
  CHANGELOG.adoc
  fhir-java/src/main/java/care/data4life/fhir/r4/json/CanonicalJsonAdapter.java
  fhir-java/src/main/java/care/data4life/fhir/r4/model/Canonical.java
  fhir-java/src/test/java/care/data4life/fhir/r4/json/CanonicalJsonAdapterTest.java
  fhir-java/src/test/java/care/data4life/fhir/r4/model/CanonicalTest.java
Labels: bug

#25 Fix Maven deployment
  buildSrc/src/main/kotlin/scripts/publishing-config.gradle.kts
Labels: bug

#28 Add codeowner file with PHDC Core KMP assignment
  .github/CODEOWNERS
Labels: enhancement

#27 Fix versioning with GitHub Action
  .github/workflows/d4l-ci-latest-version.yml
  .github/workflows/d4l-ci-pull-request-validation.yml
  buildSrc/src/main/kotlin/scripts/versioning.gradle.kts
  gradle.properties
Labels: bug
